spring:
  datasource:
    platform: mysql
    jdbc-url: jdbc:mysql://muglove.cpzhoeggzz38.ap-northeast-2.rds.amazonaws.com:3306/muglove?serverTimezone=UTC&characterEncoding=UTF-8
    username: muglove
    password: anrmffjqm4!#
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    show-sql: false
    hibernate:
      ddl-auto: create

  devtools:
    livereload:
      enabled: true
  freemarker:
    cache: false
  web:
    resources:
      static-locations: classpath:/static/


